os: osx
osx_image: xcode10.1
language: objective-c
cache: bundler

jobs:
  include:
    - stage: verify
      script: xcodebuild -showsdks
      script: instruments -s devices

    - stage: test
      script: xcodebuild test -workspace XCocoaUtilsPublic.xcworkspace -scheme DemoTests -sdk iphonesimulator #-destination 'name="iPhone X"'